server:
  port: 8080
security:
  user:
    password: user  # 直接登录时的密码
  ignored: /
  sessions: never   # session策略

  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: b8d1b536504b10abe306
      clientSecret: 5a10e5f53efbd07d30e0188aabd35479a48e2c04
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
#spring:
#  security:
#    user:
#      password: user  # 直接登录时的密码
#      name: user